name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: mentoring-system/mentoring-system.sln  # Your solution name
      Test_Project_Path: mentoring-system/test-mentoring-system/test-mentoring-system.csproj  # Your test project path
      Wap_Project_Directory: mentoring-system/mentoring-system  # Wap project directory
      Wap_Project_Path: mentoring-system/mentoring-system/mentoring-system.csproj  # Wap project path

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: mentoring-system

    - name: Checkout API Repository
      uses: actions/checkout@v4
      with:
        repository: satriadhm/api-mentoring-system
        path: mentoring-system/apimentoringsystem
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Test Repository
      uses: actions/checkout@v4
      with:
        repository: satriadhm/test-mentoring-system
        path: mentoring-system/test-mentoring-system
        token: ${{ secrets.GITHUB_TOKEN }}

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild ${{ env.Wap_Project_Path }} /p:Configuration=${{ matrix.configuration }} /p:UapAppxPackageBuildMode=${{ env.Appx_Package_Build_Mode }} /p:AppxBundle=${{ env.Appx_Bundle }} /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}

    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    # Upload the MSIX package
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
